=== codjo-sandbox/codjo-segmentation/codjo-segmentation-server/src/schema/family-list.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:appinfo>Schema segmentation</xs:appinfo>
        <xs:documentation xml:lang="fr">
            Ce schéma définit le format des fichiers permettant de configurer le
            composant codjo-segmentation.
        </xs:documentation>
    </xs:annotation>

    <!-- *************************************************************************
   |  type de base
   ************************************************************************ -->
    <xs:simpleType name="table_type">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="class_type">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="string_with_variable">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="requetor_type">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>

    <!-- *************************************************************************
   |  //family-list
   ************************************************************************ -->
    <xs:element name="family-list">
        <xs:annotation>
            <xs:documentation>Liste des préférences pour chaque famille.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="family"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- *************************************************************************
   |  //family-list/family
   ************************************************************************ -->
    <xs:element name="family">
        <xs:annotation>
            <xs:documentation>Déscription d'une famille.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="arguments"/>
                <xs:element ref="functions"/>
                <xs:element ref="delete-config"/>
                <xs:element ref="select-config"/>
                <xs:element ref="result-config"/>
                <xs:element ref="gui" minOccurs="0"/>
                <xs:element ref="select-filter" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required">
                <xs:annotation>
                    <xs:documentation>Identifiant de la famille.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="root" type="table_type" use="required">
                <xs:annotation>
                    <xs:documentation>Table source appartenant obligatoirement aux select.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="destination" type="table_type" use="required">
                <xs:annotation>
                    <xs:documentation>Table destination des résultats.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- *************************************************************************
   |  //family-list/family/arguments
   ************************************************************************ -->
    <xs:element name="arguments">
        <xs:annotation>
            <xs:documentation>
                Liste des arguments nécessaire pour lancer un traitement de cette famille.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="name" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Nom de l'argument.</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- *************************************************************************
   |  //family-list/family/functions
   ************************************************************************ -->
    <xs:element name="functions">
        <xs:annotation>
            <xs:documentation>
                Liste des fonctions holder utilisable dans un traitement de cette famille.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="holder" type="class_type">
                    <xs:annotation>
                        <xs:documentation>Classe du holder</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- *************************************************************************
   |  //family-list/family/delete-config
   ************************************************************************ -->
    <xs:element name="delete-config">
        <xs:annotation>
            <xs:documentation>
                Configuration du delete effectué avant le(s) traitement de cette famille.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="where-clause" type="string_with_variable" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Clause where du delete</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="join-key" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- *************************************************************************
   |  //family-list/family/select-config
   ************************************************************************ -->
    <xs:element name="select-config">
        <xs:annotation>
            <xs:documentation>
                Configuration du select effectué pour récuperer les données du(des)
                traitements de cette famille.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="where-clause" type="string_with_variable" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Clause where obligatoirement présente dans le select.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="join-key" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- *************************************************************************
   |  //family-list/family/result-config
   ************************************************************************ -->
    <xs:element name="result-config">
        <xs:annotation>
            <xs:documentation>
                Configuration du select effectué pour récuperer les résultats
                du(des) traitements de cette famille.
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:element name="requetor" type="requetor_type" minOccurs="0" maxOccurs="1"/>
                <xs:element name="where-clause" type="string_with_variable" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            Clause where obligatoirement présente dans le select pour les résultats.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="join-key" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="column" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="label" type="xs:string" use="required"/>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                        <xs:attribute name="table" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="join-key">
        <xs:annotation>
            <xs:documentation>
                Définition d'une jointure accessible pour la séléction des données.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="part" type="PartType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="left" type="xs:string" use="required"/>
            <xs:attribute name="type" type="JoinKeyTypeType" use="required"/>
            <xs:attribute name="right" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="JoinKeyTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="inner"/>
            <xs:enumeration value="left"/>
            <xs:enumeration value="right"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PartOperatorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="="/>
            <xs:enumeration value="!="/>
            <xs:enumeration value="&lt;&gt;"/>
            <xs:enumeration value="&lt;"/>
            <xs:enumeration value="&gt;"/>
            <xs:enumeration value="&lt;="/>
            <xs:enumeration value="&gt;="/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PartType">
        <xs:attribute name="left" type="xs:string" use="required"/>
        <xs:attribute name="operator" type="PartOperatorType" use="required"/>
        <xs:attribute name="right" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- *************************************************************************
      |  //family-list/family/gui
      ************************************************************************ -->
    <xs:element name="gui">
        <xs:annotation>
            <xs:documentation>Paramétrage spécifique à l'ihm.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="variables" minOccurs="0"/>
                <xs:element ref="filters" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="variables">
        <xs:annotation>
            <xs:documentation>
                Liste des variables disponibles dans les expressions.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="variable">
                    <xs:annotation>
                        <xs:documentation>Description de la variable.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="label" type="xs:string" use="required"/>
                        <xs:attribute name="comment" type="xs:string"/>
                        <xs:attribute name="sqlType" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="filters">
        <xs:annotation>
            <xs:documentation>
                Liste des filtres à l'affichage.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="filter">
                    <xs:annotation>
                        <xs:documentation>Description du filtre.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="table" type="xs:string" use="required"/>
                        <xs:attribute name="column" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="select-filter">
        <xs:annotation>
            <xs:documentation>Description du filtre de lignes à exclure du calcul.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="class" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== codjo-sandbox/codjo-segmentation/codjo-segmentation-release-test/src/test/resources/net/codjo/segmentation/releasetest/OneSegmentationTest-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<family-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://family-list.xsd">

    <family id="ACTION" root="SEG_INPUT" destination="SEG_RESULT">
        <arguments>
            <name>key</name>
        </arguments>

        <functions>
            <holder>net.codjo.segmentation.server.preference.family.DefaultFunctionHolder</holder>
        </functions>

        <delete-config>
            <where-clause>AXE = $segmentationId$</where-clause>
        </delete-config>

        <select-config>
            <where-clause>SEG_INPUT.MY_KEY='$key$'</where-clause>
        </select-config>
    </family>

</family-list>

=== codjo-sandbox/codjo-segmentation/codjo-segmentation-server/src/test/resources/net/codjo/segmentation/server/preference/family/XmlPreferenceLoaderTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<family-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://family-list.xsd">

    <!-- Une famille de la codification portefeuille -->
    <family id="PortfolioSegmentation" root="AP_PORTFOLIO" destination="AP_DEST_PORTFOLIO">

        <arguments>
            <name>photo</name>
            <name>segmentationId</name>
        </arguments>

        <functions>
            <holder>net.codjo.segmentation.server.preference.family.FunctionHolderMock</holder>
            <holder>net.codjo.segmentation.server.preference.family.DefaultFunctionHolder</holder>
        </functions>

        <delete-config>
            <where-clause>PHOTO = '$photo$' and AXE_ID = $segmentationId$</where-clause>
        </delete-config>

        <select-config>
            <where-clause>AP_PORTFOLIO.PHOTO='$photo$'</where-clause>

            <join-key left="AP_ROOT" type="inner" right="AP_PORTFOLIO">
                <part left="COL_R1" operator="=" right="COL_A1"/>
            </join-key>
        </select-config>

        <gui>
            <variables>
                <variable name="PTF_CONSOLIDE" label="Portefeuille"
                          comment="La var PTf de la table non nulle" sqlType="varchar"/>
                <variable name="PHOTO_CONSOLIDE" label="Photo" sqlType="int"/>
            </variables>

            <filters>
                <filter table="AP_TOTO" column="COL3"/>
                <filter table="AP_TOTO" column="COL4"/>
            </filters>
        </gui>
    </family>

    <!-- Une famille de la codification portefeuille -->
    <family id="SecuritySegmentation" root="AP_SECURITY" destination="AP_DEST_SECURITY">
        <arguments/>
        <functions/>
        <delete-config/>
        <select-config/>
    </family>

    <!-- Une famille de la codification portefeuille -->
    <family id="OutstandSegmentation" root="AP_OUTSTAND" destination="AP_DEST_OUTSTAND">
        <arguments/>
        <functions/>
        <delete-config/>
        <select-config>
            <where-clause>AP_OUTSTAND.PHOTO='$photo$'</where-clause>
            <join-key left="AP_OUTSTAND" type="inner" right="AP_SECURITY">
                <part left="PHOTO" operator="=" right="PHOTO"/>
                <part left="SECURITY_ID" operator="=" right="SECURITY_ID"/>
            </join-key>
            <join-key left="AP_SECURITY" type="left" right="AP_SECURITY_INTERNAL_FUND">
                <part left="PHOTO" operator="=" right="PHOTO"/>
                <part left="SECURITY_ID" operator="=" right="SECURITY_ID"/>
            </join-key>
        </select-config>

        <!--<select-filter class="net.codjo.segmentation.ejb.bean.DefaultFilter"/>-->
        <result-config>
            <where-clause>SEG_RESULT_EVENT.MY_KEY='$myKey$'
            </where-clause>
            <column label="Ma clé" value="MY_KEY" table="SEG_RESULT_EVENT"/>
        </result-config>
    </family>

</family-list>

=== codjo-sandbox/codjo-segmentation/codjo-segmentation-release-test/src/test/resources/META-INF/segmentation-configs.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<family-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://family-list.xsd">

    <family id="ACTION" root="SEG_INPUT_ACTION" destination="SEG_RESULT_ACTION">
        <arguments>
            <name>myKey</name>
            <name>segmentations</name>
        </arguments>

        <functions>
            <holder>net.codjo.segmentation.server.preference.family.DefaultFunctionHolder</holder>
        </functions>

        <delete-config>
            <where-clause>CLASSIFICATION_ID = $segmentationId$</where-clause>
        </delete-config>

        <select-config>
            <where-clause>SEG_INPUT_ACTION.MY_KEY='$myKey$' or '$myKey$'=''</where-clause>
        </select-config>

        <result-config>
            <!--<requetor>allSegResultAction</requetor>-->
            <where-clause>(SEG_RESULT_ACTION.ANOMALY=$anomaly$ or $anomaly$ =-1)
                      and SEG_RESULT_ACTION.CLASSIFICATION_ID = $segmentationId$
                      and (SEG_RESULT_ACTION.MY_KEY='$myKey$' or '$myKey$'='')
            </where-clause>
            <column label="Ma clé" value="MY_KEY" table="SEG_RESULT_ACTION"/>
        </result-config>
        <gui>
            <variables>
                <variable name="VAR_myVariable" label="Ma variable" sqlType="varchar"/>
            </variables>
        </gui>
    </family>
    <family id="EVENT" root="SEG_INPUT_EVENT" destination="SEG_RESULT_EVENT">
        <arguments>
            <name>myKey</name>
            <name>segmentations</name>
        </arguments>

        <functions>
            <holder>net.codjo.segmentation.server.preference.family.DefaultFunctionHolder</holder>
        </functions>

        <delete-config>
            <where-clause>CLASSIFICATION_ID = $segmentationId$</where-clause>
        </delete-config>

        <select-config>
            <where-clause>SEG_INPUT_EVENT.MY_KEY='$myKey$' or '$myKey$'=''</where-clause>
        </select-config>

        <result-config>
            <!--<requetor>allSegResultEvent</requetor>-->
            <where-clause>(SEG_RESULT_EVENT.ANOMALY=$anomaly$ or $anomaly$ =-1)
                      and SEG_RESULT_EVENT.CLASSIFICATION_ID = $segmentationId$
                      and (SEG_RESULT_EVENT.MY_KEY='$myKey$' or '$myKey$'='')
            </where-clause>
            <column label="Ma clé" value="MY_KEY" table="SEG_RESULT_EVENT"/>
        </result-config>
    </family>
    <family id="REQUETOR" root="SEG_INPUT_REQUETOR" destination="SEG_RESULT_REQUETOR">
        <arguments>
            <name>myKey</name>
            <name>segmentations</name>
        </arguments>

        <functions>
            <holder>net.codjo.segmentation.server.preference.family.DefaultFunctionHolder</holder>
        </functions>

        <delete-config>
            <where-clause>CLASSIFICATION_ID = $segmentationId$</where-clause>
        </delete-config>

        <select-config>
            <where-clause>SEG_INPUT_REQUETOR.MY_KEY='$myKey$' or '$myKey$'=''</where-clause>
        </select-config>

        <result-config>
            <requetor>allSegResultRequetor</requetor>
            <where-clause>(SEG_RESULT_REQUETOR.ANOMALY=$anomaly$ or $anomaly$ =-1)
                and SEG_RESULT_REQUETOR.CLASSIFICATION_ID = $segmentationId$
                and (SEG_RESULT_REQUETOR.MY_KEY='$myKey$' or '$myKey$'='')
            </where-clause>
            <join-key left="SEG_RESULT_REQUETOR" type="inner" right="PM_CLASSIFICATION">
                <part left="CLASSIFICATION_ID" operator="=" right="CLASSIFICATION_ID"/>                
            </join-key>
              <join-key left="SEG_RESULT_REQUETOR" type="inner" right="PM_CLASSIFICATION_STRUCTURE">
                <part left="CLASSIFICATION_ID" operator="=" right="CLASSIFICATION_ID"/>
                <part left="SLEEVE_CODE" operator="=" right="SLEEVE_CODE"/>
            </join-key>
            <column label="Ma clé" value="MY_KEY" table="SEG_RESULT_REQUETOR"/>
            <column label="Libellé axe" value="CLASSIFICATION_NAME" table="PM_CLASSIFICATION"/>
             <column label="Code poche" value="SLEEVE_CODE" table="SEG_RESULT_REQUETOR"/>
             <column label="Libellé poche" value="SLEEVE_NAME" table="PM_CLASSIFICATION_STRUCTURE"/>
        </result-config>
    </family>

</family-list>
